import requests

API = "https://sacad-api.onrender.com"

attacks = [
    {"title": "India Paytm KYC Vishing Scam", "description": "Widespread vishing impersonating Paytm KYC agents tricking victims into installing remote access tools.", "attack_type": "social_engineering", "attack_vector": "phone", "target_sector": "banking", "country": "India", "severity": "medium", "source_name": "CERT-In", "status": "verified", "verified": "yes", "confidence_score": 0.87},
    {"title": "Nepal Himalayan Bank ATM Skimming", "description": "Coordinated ATM skimming targeting Himalayan Bank. Over 200 customers reported fraudulent transactions.", "attack_type": "other", "attack_vector": "unknown", "target_sector": "banking", "country": "Nepal", "severity": "high", "source_name": "Nepal Police", "status": "verified", "verified": "yes", "confidence_score": 0.85},
    {"title": "India SBI Card 1 Million Customer Breach", "description": "Data of 1 million SBI Card customers including partial card details found on dark web.", "attack_type": "data_breach", "attack_vector": "unknown", "target_sector": "banking", "country": "India", "severity": "high", "source_name": "Business Standard", "status": "verified", "verified": "yes", "confidence_score": 0.87},
    {"title": "Pakistan FIA Cybercrime Wing Defacement", "description": "Ironic defacement of Pakistan FIA Cybercrime Wing website with taunting message.", "attack_type": "defacement", "attack_vector": "web", "target_sector": "government", "country": "Pakistan", "severity": "medium", "source_name": "The News Pakistan", "status": "verified", "verified": "yes", "confidence_score": 0.91},
    {"title": "Nepal Rastriya Banijya Bank Phishing", "description": "Phishing campaign targeting RBB customers via SMS and email. Multiple unauthorized transactions.", "attack_type": "phishing", "attack_vector": "sms", "target_sector": "banking", "country": "Nepal", "severity": "high", "source_name": "CERT-NP", "status": "verified", "verified": "yes", "confidence_score": 0.86},
    {"title": "India Haldirams Ransomware Attack", "description": "Ransomware encrypted critical business data of Haldirams. Company filed complaint with CBI.", "attack_type": "ransomware", "attack_vector": "unknown", "target_sector": "ecommerce", "country": "India", "severity": "medium", "source_name": "Economic Times", "status": "verified", "verified": "yes", "confidence_score": 0.81},
    {"title": "Bangladesh Sonali Bank Malware Attack", "description": "Malware infection on Sonali Bank network compromised employee workstations.", "attack_type": "malware", "attack_vector": "email", "target_sector": "banking", "country": "Bangladesh", "severity": "high", "source_name": "BGD e-GOV CIRT", "status": "verified", "verified": "yes", "confidence_score": 0.85},
    {"title": "Nepal Army Website DDoS Attack", "description": "DDoS attack targeting Nepal Army website taking it offline for several hours.", "attack_type": "ddos", "attack_vector": "web", "target_sector": "government", "country": "Nepal", "severity": "medium", "source_name": "Setopati", "status": "verified", "verified": "partial", "confidence_score": 0.80},
    {"title": "India Mathway Education App 25 Million Breach", "description": "25 million Mathway education app user records stolen including hashed passwords.", "attack_type": "data_breach", "attack_vector": "web", "target_sector": "education", "country": "India", "severity": "medium", "source_name": "ZDNet", "status": "verified", "verified": "yes", "confidence_score": 0.90},
    {"title": "Pakistan HBL Banking Malware Campaign", "description": "Fake HBL mobile banking apps harvesting credentials and performing fraudulent transfers.", "attack_type": "malware", "attack_vector": "web", "target_sector": "banking", "country": "Pakistan", "severity": "high", "malware_family": "BankBot", "source_name": "CERT Pakistan", "status": "verified", "verified": "yes", "confidence_score": 0.84},
    {"title": "India Dunzo Quick Commerce Breach", "description": "Personal data of 3.5 million Dunzo users exposed including phone numbers and delivery addresses.", "attack_type": "data_breach", "attack_vector": "web", "target_sector": "ecommerce", "country": "India", "severity": "medium", "source_name": "Cyble", "status": "verified", "verified": "yes", "confidence_score": 0.86},
    {"title": "Dhaka Stock Exchange DDoS Attack", "description": "DDoS attack on Dhaka Stock Exchange disrupted online trading during peak hours.", "attack_type": "ddos", "attack_vector": "web", "target_sector": "banking", "country": "Bangladesh", "severity": "medium", "source_name": "Financial Express Bangladesh", "status": "verified", "verified": "yes", "confidence_score": 0.81},
    {"title": "Nepal Ministry of Foreign Affairs Email Compromise", "description": "Business email compromise on Nepal Ministry of Foreign Affairs intercepting diplomatic communications.", "attack_type": "social_engineering", "attack_vector": "email", "target_sector": "government", "country": "Nepal", "severity": "high", "source_name": "CERT-NP", "status": "verified", "verified": "partial", "confidence_score": 0.80},
    {"title": "India ONGC Oil Company Cyber Intrusion", "description": "Targeted cyber intrusion on ONGC internal network exfiltrating geological survey data.", "attack_type": "data_breach", "attack_vector": "unknown", "target_sector": "government", "country": "India", "severity": "high", "source_name": "Economic Times", "status": "verified", "verified": "partial", "confidence_score": 0.80},
    {"title": "Pakistan OGDCL Oil Company Cyber Attack", "description": "OGDCL Pakistan suffered cyberattack disrupting internal operations and data management.", "attack_type": "malware", "attack_vector": "unknown", "target_sector": "government", "country": "Pakistan", "severity": "high", "source_name": "Dawn", "status": "verified", "verified": "yes", "confidence_score": 0.83},
    {"title": "Sri Lanka Central Bank SWIFT Incident", "description": "Central Bank of Sri Lanka reported SWIFT security incident. Suspicious transactions blocked.", "attack_type": "data_breach", "attack_vector": "unknown", "target_sector": "banking", "country": "Sri Lanka", "severity": "critical", "source_name": "Daily Mirror Sri Lanka", "status": "verified", "verified": "partial", "confidence_score": 0.81},
    {"title": "India Swiggy Credential Stuffing Attack", "description": "Credential stuffing on Swiggy accounts using leaked credentials. Thousands of accounts hijacked.", "attack_type": "other", "attack_vector": "web", "target_sector": "ecommerce", "country": "India", "severity": "medium", "source_name": "CERT-In", "status": "verified", "verified": "yes", "confidence_score": 0.84},
    {"title": "Pakistan PIA Airline Data Breach", "description": "Pakistan International Airlines breach exposing employee records and internal communications.", "attack_type": "data_breach", "attack_vector": "unknown", "target_sector": "government", "country": "Pakistan", "severity": "medium", "source_name": "ARY News", "status": "verified", "verified": "yes", "confidence_score": 0.82},
    {"title": "Bangladesh Rupali Bank Phishing Attack", "description": "State-owned Rupali Bank customers targeted by phishing. Multiple unauthorized transactions.", "attack_type": "phishing", "attack_vector": "email", "target_sector": "banking", "country": "Bangladesh", "severity": "high", "source_name": "BGD e-GOV CIRT", "status": "verified", "verified": "yes", "confidence_score": 0.86},
    {"title": "Bhutan Government Portal Defacement", "description": "Multiple Bhutanese government websites including Royal Civil Service Commission defaced.", "attack_type": "defacement", "attack_vector": "web", "target_sector": "government", "country": "Bhutan", "severity": "low", "source_name": "Zone-H", "status": "verified", "verified": "partial", "confidence_score": 0.78},
    {"title": "India Tribhuvan University Network Compromise", "description": "Tribhuvan University network compromised exposing data of 300,000 students.", "attack_type": "data_breach", "attack_vector": "web", "target_sector": "education", "country": "Nepal", "severity": "high", "source_name": "CERT-NP", "status": "verified", "verified": "partial", "confidence_score": 0.79},
    {"title": "India BSNL 2.9 Million Subscriber Breach", "description": "Data of 2.9 million BSNL subscribers leaked by threat actor USDoD.", "attack_type": "data_breach", "attack_vector": "unknown", "target_sector": "telecom", "country": "India", "severity": "high", "source_name": "Cyble", "status": "verified", "verified": "yes", "confidence_score": 0.91},
    {"title": "India Truecaller 4.75 Million Data Sale", "description": "Data of 4.75 million Indian Truecaller users listed for sale on dark web.", "attack_type": "data_breach", "attack_vector": "web", "target_sector": "telecom", "country": "India", "severity": "medium", "source_name": "Cyble", "status": "verified", "verified": "yes", "confidence_score": 0.87},
    {"title": "Nepal Citizen Investment Trust Data Exposure", "description": "Personal and financial data of investors exposed through misconfigured portal.", "attack_type": "data_breach", "attack_vector": "web", "target_sector": "banking", "country": "Nepal", "severity": "high", "source_name": "CERT-NP", "status": "verified", "verified": "partial", "confidence_score": 0.79},
    {"title": "Pakistan Daraz E-Commerce Data Breach", "description": "Data of millions of Daraz Pakistan customers exposed including order history.", "attack_type": "data_breach", "attack_vector": "web", "target_sector": "ecommerce", "country": "Pakistan", "severity": "high", "source_name": "Propakistani", "status": "verified", "verified": "yes", "confidence_score": 0.83},
    {"title": "India ICICI Bank SMS Phishing Campaign", "description": "Mass SMS phishing impersonating ICICI Bank stealing banking passwords and OTPs.", "attack_type": "phishing", "attack_vector": "sms", "target_sector": "banking", "country": "India", "severity": "high", "source_name": "CERT-In", "status": "verified", "verified": "yes", "confidence_score": 0.91},
    {"title": "India AIIMS Rishikesh Ransomware", "description": "Third major ransomware attack on Indian AIIMS hospitals affecting OPD and diagnostics.", "attack_type": "ransomware", "attack_vector": "unknown", "target_sector": "healthcare", "country": "India", "severity": "critical", "source_name": "CERT-In", "status": "verified", "verified": "yes", "confidence_score": 0.89},
    {"title": "Pakistan Meezan Bank Fake App Fraud", "description": "Fake Meezan Bank app collected credentials of thousands of Islamic banking customers.", "attack_type": "malware", "attack_vector": "web", "target_sector": "banking", "country": "Pakistan", "severity": "high", "source_name": "CERT Pakistan", "status": "verified", "verified": "yes", "confidence_score": 0.83},
    {"title": "Nepal Pokhara University Website Defacement", "description": "Pokhara University official website defaced by hackers with political messaging.", "attack_type": "defacement", "attack_vector": "web", "target_sector": "education", "country": "Nepal", "severity": "low", "source_name": "Gandaki Media", "status": "verified", "verified": "partial", "confidence_score": 0.78},
    {"title": "India DriveU Driver Data Breach", "description": "Personal data of 3 million DriveU drivers exposed including Aadhaar and bank details.", "attack_type": "data_breach", "attack_vector": "web", "target_sector": "ecommerce", "country": "India", "severity": "high", "source_name": "Cyble", "status": "verified", "verified": "yes", "confidence_score": 0.86},
    {"title": "Bangladesh DGDA Pharmaceutical Breach", "description": "DGDA Bangladesh website breached exposing drug registration data and internal communications.", "attack_type": "data_breach", "attack_vector": "web", "target_sector": "healthcare", "country": "Bangladesh", "severity": "medium", "source_name": "BGD e-GOV CIRT", "status": "verified", "verified": "yes", "confidence_score": 0.83},
    {"title": "India Paytm KYC Fake App Campaign", "description": "Fake Paytm KYC apps on third party stores stealing payment credentials from millions.", "attack_type": "malware", "attack_vector": "web", "target_sector": "banking", "country": "India", "severity": "high", "source_name": "CERT-In", "status": "verified", "verified": "yes", "confidence_score": 0.88},
    {"title": "Pakistan Sensitive Government Documents Leaked", "description": "Hackers leaked sensitive Pakistani government documents on dark web forums.", "attack_type": "data_breach", "attack_vector": "unknown", "target_sector": "government", "country": "Pakistan", "severity": "critical", "source_name": "Dawn", "status": "verified", "verified": "yes", "confidence_score": 0.87},
    {"title": "Bangladesh 50 Government Websites Defaced", "description": "Hacktivist group defaced over 50 Bangladeshi government websites simultaneously.", "attack_type": "defacement", "attack_vector": "web", "target_sector": "government", "country": "Bangladesh", "severity": "medium", "source_name": "BGD e-GOV CIRT", "status": "verified", "verified": "partial", "confidence_score": 0.82},
    {"title": "Nepal Ncell Telecom Phishing 2024", "description": "Phishing campaign impersonating Ncell operator collecting telecom credentials.", "attack_type": "phishing", "attack_vector": "sms", "target_sector": "telecom", "country": "Nepal", "severity": "high", "source_name": "CERT-NP", "status": "verified", "verified": "yes", "confidence_score": 0.86},
    {"title": "India IRCTC Railway Booking Phishing", "description": "Large scale phishing impersonating IRCTC with fake ticket booking pages.", "attack_type": "phishing", "attack_vector": "email", "target_sector": "government", "country": "India", "severity": "medium", "source_name": "CERT-In", "status": "verified", "verified": "yes", "confidence_score": 0.89},
    {"title": "Pakistan NADRA Database Breach Attempt", "description": "Attempted breach of Pakistan NADRA database containing biometric data of 120 million citizens.", "attack_type": "other", "attack_vector": "web", "target_sector": "government", "country": "Pakistan", "severity": "critical", "source_name": "The News Pakistan", "status": "verified", "verified": "partial", "confidence_score": 0.79},
    {"title": "India Rastriya Beema Insurance Data Breach", "description": "Personal and financial data of Rastriya Beema Company Nepal policyholders exposed.", "attack_type": "data_breach", "attack_vector": "web", "target_sector": "banking", "country": "Nepal", "severity": "medium", "source_name": "CERT-NP", "status": "verified", "verified": "partial", "confidence_score": 0.77},
    {"title": "Sri Lanka Government Ministry Phishing", "description": "Spear phishing targeting Sri Lanka government officials via fake Ministry of Finance emails.", "attack_type": "phishing", "attack_vector": "email", "target_sector": "government", "country": "Sri Lanka", "severity": "high", "source_name": "CERT-CC Sri Lanka", "status": "verified", "verified": "yes", "confidence_score": 0.82},
    {"title": "India BigBasket Credential Stuffing", "description": "Credential stuffing on BigBasket using leaked credentials. Thousands of accounts hijacked.", "attack_type": "other", "attack_vector": "web", "target_sector": "ecommerce", "country": "India", "severity": "medium", "source_name": "CERT-In", "status": "verified", "verified": "yes", "confidence_score": 0.84},
    {"title": "Nepal Prime Minister Office Defacement", "description": "Official website of Nepal Prime Minister Office defaced with political messaging.", "attack_type": "defacement", "attack_vector": "web", "target_sector": "government", "country": "Nepal", "severity": "medium", "source_name": "Onlinekhabar", "status": "verified", "verified": "partial", "confidence_score": 0.82},
]

for a in attacks:
    res = requests.post(f"{API}/attacks", json=a)
    print(f"{res.status_code} - {a['title'][:50]}")

print(f"\nDone!")