import sys, os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from app.database import SessionLocal, engine
from app import models
models.Base.metadata.create_all(bind=engine)

ATTACKS = [
    {"title": "Bangladesh Bank SWIFT Heist", "description": "Lazarus Group compromised Bangladesh Bank SWIFT terminal stealing $81 million routed to Philippines accounts.", "attack_type": "data_breach", "attack_vector": "email", "target_sector": "banking", "country": "Bangladesh", "severity": "critical", "threat_actor": "Lazarus Group", "source_name": "SWIFT", "status": "verified", "confidence_score": 0.99, "verified": "yes"},
    {"title": "Kudankulam Nuclear Plant DTRACK Malware", "description": "DTRACK malware linked to Lazarus Group found on administrative network of Kudankulam Nuclear Power Plant in Tamil Nadu.", "attack_type": "malware", "attack_vector": "unknown", "target_sector": "government", "country": "India", "severity": "critical", "threat_actor": "Lazarus Group", "malware_family": "DTRACK", "source_name": "NPCIL", "status": "verified", "confidence_score": 0.94, "verified": "yes"},
    {"title": "Aadhaar Biometric Database Breach", "description": "Access to Aadhaar database containing biometric data of 1.1 billion Indians was sold via WhatsApp for Rs 500.", "attack_type": "data_breach", "attack_vector": "insider", "target_sector": "government", "country": "India", "severity": "critical", "source_name": "Tribune India", "status": "verified", "confidence_score": 0.96, "verified": "yes"},
    {"title": "AIIMS Delhi Ransomware Attack", "description": "Ransomware crippled AIIMS Delhi for 15+ days encrypting records of 3-4 crore patients. Staff reverted to manual processes.", "attack_type": "ransomware", "attack_vector": "unknown", "target_sector": "healthcare", "country": "India", "region": "New Delhi", "severity": "critical", "target_org": "AIIMS Delhi", "source_name": "CERT-In", "status": "verified", "confidence_score": 0.98, "verified": "yes"},
    {"title": "Air India Passenger Data Breach via SITA", "description": "4.5 million Air India passengers affected by breach of SITA Passenger Service System including passport and credit card data.", "attack_type": "data_breach", "attack_vector": "supply_chain", "target_sector": "government", "country": "India", "severity": "high", "source_name": "Air India", "status": "verified", "confidence_score": 0.95, "verified": "yes"},
    {"title": "MobiKwik Payment Platform Breach", "description": "3.5 million KYC details and 8.2 TB of user data stolen from MobiKwik including Aadhaar and PAN card numbers.", "attack_type": "data_breach", "attack_vector": "web", "target_sector": "banking", "country": "India", "severity": "high", "source_name": "Cyble", "status": "verified", "confidence_score": 0.93, "verified": "yes"},
    {"title": "BigBasket Customer Data Breach", "description": "20 million BigBasket user records including password hashes and addresses found for sale on dark web for $40,000.", "attack_type": "data_breach", "attack_vector": "web", "target_sector": "ecommerce", "country": "India", "severity": "high", "source_name": "Cyble", "status": "verified", "confidence_score": 0.92, "verified": "yes"},
    {"title": "Dominos India 180 Million Order Data Leak", "description": "180 million Dominos India order records including names, phone numbers, and payment details made searchable on dark web portal.", "attack_type": "data_breach", "attack_vector": "web", "target_sector": "ecommerce", "country": "India", "severity": "high", "source_name": "TechCrunch", "status": "verified", "confidence_score": 0.94, "verified": "yes"},
    {"title": "NIC Asia Bank SWIFT Heist Nepal", "description": "Hackers siphoned NPR 460 million from NIC Asia Bank by compromising SWIFT system. Funds transferred to USA, UK, Japan, Singapore.", "attack_type": "data_breach", "attack_vector": "unknown", "target_sector": "banking", "country": "Nepal", "severity": "critical", "target_org": "NIC Asia Bank", "source_name": "Kathmandu Post", "status": "verified", "confidence_score": 0.97, "verified": "yes"},
    {"title": "Nepal Telecom Customer Phishing Campaign", "description": "Mass phishing SMS impersonating Nepal Telecom luring users to fake login pages to harvest credentials.", "attack_type": "phishing", "attack_vector": "sms", "target_sector": "telecom", "country": "Nepal", "severity": "high", "ioc_urls": "hxxp://ntc-verify[.]com/login", "ioc_ips": "185.220.101[.]45", "source_name": "CERT-NP", "status": "verified", "confidence_score": 0.95, "verified": "yes"},
    {"title": "Pakistan FBR 115 Million User Data Leak", "description": "Data of 115 million Pakistani mobile users leaked from Federal Board of Revenue portal including CNICs and addresses.", "attack_type": "data_breach", "attack_vector": "web", "target_sector": "government", "country": "Pakistan", "severity": "critical", "target_org": "FBR Pakistan", "source_name": "Dawn", "status": "verified", "confidence_score": 0.85, "verified": "partial"},
    {"title": "AIIMS Patna Ransomware Attack", "description": "Second major ransomware attack on Indian AIIMS hospital disrupting patient management, billing, and lab systems.", "attack_type": "ransomware", "attack_vector": "unknown", "target_sector": "healthcare", "country": "India", "region": "Patna, Bihar", "severity": "high", "target_org": "AIIMS Patna", "source_name": "CERT-In", "status": "verified", "confidence_score": 0.90, "verified": "yes"},
    {"title": "CoWIN Vaccine Data Leak India", "description": "Telegram bot exposed Aadhaar numbers, phone numbers, and vaccination details of millions of Indians from CoWIN portal.", "attack_type": "data_breach", "attack_vector": "web", "target_sector": "healthcare", "country": "India", "severity": "high", "target_org": "CoWIN Ministry of Health", "source_name": "CERT-In", "status": "verified", "confidence_score": 0.91, "verified": "yes"},
    {"title": "ICMR COVID Data 815 Million Records Breach", "description": "Personal data of 815 million Indians from ICMR COVID testing database listed for sale on dark web including Aadhaar and passport details.", "attack_type": "data_breach", "attack_vector": "unknown", "target_sector": "healthcare", "country": "India", "severity": "critical", "target_org": "ICMR", "source_name": "Resecurity", "status": "verified", "confidence_score": 0.90, "verified": "yes"},
    {"title": "Juspay Payment Gateway 35 Million Cards Breach", "description": "35 million card records stolen from Juspay payment gateway used by Amazon, Swiggy, MakeMyTrip.", "attack_type": "data_breach", "attack_vector": "web", "target_sector": "banking", "country": "India", "severity": "critical", "target_org": "Juspay", "source_name": "Rajshekhar Rajaharia", "status": "verified", "confidence_score": 0.95, "verified": "yes"},
    {"title": "K-Electric Karachi Netwalker Ransomware", "description": "Netwalker ransomware hit K-Electric, Karachi sole power provider, disrupting billing. Attackers demanded $3.85 million ransom.", "attack_type": "ransomware", "attack_vector": "unknown", "target_sector": "government", "country": "Pakistan", "severity": "critical", "target_org": "K-Electric", "malware_family": "Netwalker", "source_name": "BleepingComputer", "status": "verified", "confidence_score": 0.95, "verified": "yes"},
    {"title": "Pakistan K-Electric Data Leak After Ransomware", "description": "After K-Electric refused to pay ransom, Netwalker operators leaked 8.5GB of stolen data including employee and financial records.", "attack_type": "data_breach", "attack_vector": "unknown", "target_sector": "government", "country": "Pakistan", "severity": "high", "target_org": "K-Electric", "source_name": "BleepingComputer", "status": "verified", "confidence_score": 0.93, "verified": "yes"},
    {"title": "Unacademy 22 Million Users Data Breach", "description": "22 million Unacademy user records including usernames, hashed passwords, and email addresses listed for sale on dark web.", "attack_type": "data_breach", "attack_vector": "web", "target_sector": "education", "country": "India", "severity": "high", "target_org": "Unacademy", "source_name": "Cyble", "status": "verified", "confidence_score": 0.92, "verified": "yes"},
    {"title": "Upstox 2.5 Million KYC Data Breach", "description": "KYC data of 2.5 million Upstox stock trading users including Aadhaar and PAN cards compromised. Attacker contacted users directly.", "attack_type": "data_breach", "attack_vector": "web", "target_sector": "banking", "country": "India", "severity": "high", "target_org": "Upstox", "source_name": "Upstox", "status": "verified", "confidence_score": 0.94, "verified": "yes"},
    {"title": "BSNL 2.9 Million Subscriber Data Breach", "description": "Data of 2.9 million BSNL subscribers including email addresses and billing details leaked by threat actor USDoD.", "attack_type": "data_breach", "attack_vector": "unknown", "target_sector": "telecom", "country": "India", "severity": "high", "target_org": "BSNL", "source_name": "Cyble", "status": "verified", "confidence_score": 0.91, "verified": "yes"},
    {"title": "Bangladesh Election Commission 50 Million Voter Data Exposure", "description": "Personal data of 50 million Bangladeshi voters exposed via unsecured Election Commission website including national IDs and birth dates.", "attack_type": "data_breach", "attack_vector": "web", "target_sector": "government", "country": "Bangladesh", "severity": "high", "source_name": "TechCrunch", "status": "verified", "confidence_score": 0.93, "verified": "yes"},
    {"title": "Dutch-Bangla Bank ATM Network Hack", "description": "Hackers compromised Dutch-Bangla Bank ATM network stealing Tk 25 crore using cloned cards in coordinated overnight attack.", "attack_type": "malware", "attack_vector": "unknown", "target_sector": "banking", "country": "Bangladesh", "severity": "critical", "target_org": "Dutch-Bangla Bank", "source_name": "BGD e-GOV CIRT", "status": "verified", "confidence_score": 0.93, "verified": "yes"},
    {"title": "SpiceJet Airlines Ransomware Attack", "description": "Ransomware attack on SpiceJet caused flight delays and disrupted booking systems for thousands of passengers.", "attack_type": "ransomware", "attack_vector": "unknown", "target_sector": "government", "country": "India", "severity": "high", "target_org": "SpiceJet Airlines", "source_name": "Times of India", "status": "verified", "confidence_score": 0.89, "verified": "yes"},
    {"title": "Nepal eSewa Digital Wallet Phishing", "description": "Phishing SMS campaign targeting eSewa wallet users via fake account suspension alerts directing to cloned login pages.", "attack_type": "phishing", "attack_vector": "sms", "target_sector": "banking", "country": "Nepal", "severity": "medium", "target_org": "eSewa customers", "ioc_urls": "hxxp://esewa-verify[.]com", "source_name": "CERT-NP", "status": "verified", "confidence_score": 0.88, "verified": "yes"},
    {"title": "Nepal Government Portal Defacement Campaign", "description": "Coordinated defacement of 12+ Nepal government subdomains including moha.gov.np replacing content with political messaging.", "attack_type": "defacement", "attack_vector": "web", "target_sector": "government", "country": "Nepal", "region": "Kathmandu", "severity": "medium", "source_name": "CERT-NP", "status": "verified", "confidence_score": 0.88, "verified": "partial"},
    {"title": "India SBI Card 1 Million Customer Data Breach", "description": "Data of 1 million SBI Card customers including partial card details found for sale on dark web forums.", "attack_type": "data_breach", "attack_vector": "unknown", "target_sector": "banking", "country": "India", "severity": "high", "target_org": "SBI Card", "source_name": "Business Standard", "status": "verified", "confidence_score": 0.87, "verified": "yes"},
    {"title": "Tribhuvan University Nepal Network Compromise", "description": "Tribhuvan University network compromised exposing student records, exam results, and administrative data of 300,000 students.", "attack_type": "data_breach", "attack_vector": "web", "target_sector": "education", "country": "Nepal", "severity": "high", "target_org": "Tribhuvan University", "source_name": "CERT-NP", "status": "verified", "confidence_score": 0.79, "verified": "partial"},
    {"title": "Pakistan HBL Banking Malware Campaign", "description": "Fake HBL mobile banking apps distributed through third-party stores harvesting credentials and performing fraudulent transfers.", "attack_type": "malware", "attack_vector": "web", "target_sector": "banking", "country": "Pakistan", "severity": "high", "target_org": "HBL customers", "malware_family": "BankBot", "source_name": "CERT Pakistan", "status": "verified", "confidence_score": 0.84, "verified": "yes"},
    {"title": "India Haldirams Ransomware Attack", "description": "Ransomware attack encrypted critical business data of Haldirams snacks company. Company filed complaint with CBI cybercrime unit.", "attack_type": "ransomware", "attack_vector": "unknown", "target_sector": "ecommerce", "country": "India", "severity": "medium", "target_org": "Haldirams", "source_name": "Economic Times", "status": "verified", "confidence_score": 0.81, "verified": "yes"},
    {"title": "BRAC Bank Bangladesh Phishing Campaign", "description": "Sophisticated phishing campaign targeting BRAC Bank customers. Over 500 customers reported credential theft and unauthorized transactions.", "attack_type": "phishing", "attack_vector": "sms", "target_sector": "banking", "country": "Bangladesh", "severity": "high", "target_org": "BRAC Bank customers", "source_name": "BGD e-GOV CIRT", "status": "verified", "confidence_score": 0.87, "verified": "yes"},
    {"title": "India Drinik Android Banking Trojan", "description": "Drinik v3 Android trojan via fake IT Department APK targeted customers of SBI, ICICI, HDFC and 15 other Indian banks.", "attack_type": "malware", "attack_vector": "web", "target_sector": "banking", "country": "India", "severity": "critical", "malware_family": "Drinik", "ioc_ips": "91.219.213[.]44", "source_name": "CERT-In", "status": "verified", "confidence_score": 0.97, "verified": "yes"},
    {"title": "Pakistan FIA Cybercrime Wing Website Defacement", "description": "Ironic defacement of Pakistan FIA Cybercrime Wing website with taunting message about government cybersecurity failures.", "attack_type": "defacement", "attack_vector": "web", "target_sector": "government", "country": "Pakistan", "severity": "medium", "target_org": "FIA Pakistan", "source_name": "The News Pakistan", "status": "verified", "confidence_score": 0.91, "verified": "yes"},
    {"title": "Nepal Rastriya Banijya Bank Phishing", "description": "Phishing campaign targeting RBB customers via SMS and email. Multiple customers reported unauthorized transactions.", "attack_type": "phishing", "attack_vector": "sms", "target_sector": "banking", "country": "Nepal", "severity": "high", "target_org": "RBB customers", "source_name": "CERT-NP", "status": "verified", "confidence_score": 0.86, "verified": "yes"},
    {"title": "Telenor Pakistan 44 Million Subscriber Data Breach", "description": "Personal data of 44 million Telenor Pakistan subscribers exposed including CNIC numbers, addresses, and SIM activation details.", "attack_type": "data_breach", "attack_vector": "unknown", "target_sector": "telecom", "country": "Pakistan", "severity": "critical", "target_org": "Telenor Pakistan", "source_name": "Propakistani", "status": "verified", "confidence_score": 0.88, "verified": "yes"},
    {"title": "India IRCTC Railway Booking Phishing", "description": "Large scale phishing impersonating IRCTC with fake ticket booking pages. Victims lost payment credentials.", "attack_type": "phishing", "attack_vector": "email", "target_sector": "government", "country": "India", "severity": "medium", "target_org": "IRCTC customers", "source_name": "CERT-In", "status": "verified", "confidence_score": 0.89, "verified": "yes"},
    {"title": "Bangladesh DGDA Pharmaceutical Data Breach", "description": "DGDA Bangladesh website breached exposing drug registration data and internal communications.", "attack_type": "data_breach", "attack_vector": "web", "target_sector": "healthcare", "country": "Bangladesh", "severity": "medium", "target_org": "DGDA Bangladesh", "source_name": "BGD e-GOV CIRT", "status": "verified", "confidence_score": 0.83, "verified": "yes"},
    {"title": "India Paytm KYC Vishing Scam", "description": "Widespread vishing impersonating Paytm KYC agents tricking victims into installing remote access tools and sharing OTPs.", "attack_type": "social_engineering", "attack_vector": "phone", "target_sector": "banking", "country": "India", "severity": "medium", "target_org": "Paytm customers", "source_name": "CERT-In", "status": "verified", "confidence_score": 0.87, "verified": "yes"},
    {"title": "Nepal Himalayan Bank ATM Skimming Campaign", "description": "Coordinated ATM skimming and card cloning targeting Himalayan Bank ATMs. Over 200 customers reported fraudulent transactions.", "attack_type": "other", "attack_vector": "unknown", "target_sector": "banking", "country": "Nepal", "severity": "high", "target_org": "Himalayan Bank", "source_name": "Nepal Police", "status": "verified", "confidence_score": 0.85, "verified": "yes"},
    {"title": "AIIMS Rishikesh Ransomware Attack", "description": "Third major ransomware attack on Indian AIIMS hospitals affecting OPD services, patient records, and diagnostics.", "attack_type": "ransomware", "attack_vector": "unknown", "target_sector": "healthcare", "country": "India", "region": "Rishikesh", "severity": "critical", "target_org": "AIIMS Rishikesh", "source_name": "CERT-In", "status": "verified", "confidence_score": 0.89, "verified": "yes"},
    {"title": "Pakistan Meezan Bank Fake App Fraud", "description": "Fake Meezan Bank mobile app collected credentials of thousands of Islamic banking customers and facilitated unauthorized transfers.", "attack_type": "malware", "attack_vector": "web", "target_sector": "banking", "country": "Pakistan", "severity": "high", "target_org": "Meezan Bank customers", "source_name": "CERT Pakistan", "status": "verified", "confidence_score": 0.83, "verified": "yes"},
    {"title": "India BigBasket Credential Stuffing Attack", "description": "Credential stuffing attack on BigBasket using leaked credentials. Thousands of accounts hijacked for fraudulent orders.", "attack_type": "other", "attack_vector": "web", "target_sector": "ecommerce", "country": "India", "severity": "medium", "target_org": "BigBasket", "source_name": "CERT-In", "status": "verified", "confidence_score": 0.84, "verified": "yes"},
    {"title": "Sri Lanka Government Ministry Phishing", "description": "Spear phishing targeting Sri Lanka government officials via fake Ministry of Finance emails harvesting credentials.", "attack_type": "phishing", "attack_vector": "email", "target_sector": "government", "country": "Sri Lanka", "severity": "high", "source_name": "CERT-CC Sri Lanka", "status": "verified", "confidence_score": 0.82, "verified": "yes"},
    {"title": "Dhaka Stock Exchange DDoS Attack", "description": "DDoS attack on Dhaka Stock Exchange disrupted online trading access for retail investors during peak trading hours.", "attack_type": "ddos", "attack_vector": "web", "target_sector": "banking", "country": "Bangladesh", "severity": "medium", "target_org": "Dhaka Stock Exchange", "source_name": "Financial Express Bangladesh", "status": "verified", "confidence_score": 0.81, "verified": "yes"},
    {"title": "Nepal Ministry of Foreign Affairs Email Compromise", "description": "Business email compromise on Nepal Ministry of Foreign Affairs intercepting diplomatic communications and attempting financial fraud.", "attack_type": "social_engineering", "attack_vector": "email", "target_sector": "government", "country": "Nepal", "severity": "high", "target_org": "Nepal Ministry of Foreign Affairs", "source_name": "CERT-NP", "status": "verified", "confidence_score": 0.80, "verified": "partial"},
    {"title": "India ONGC Oil Company Cyber Intrusion", "description": "Targeted cyber intrusion on ONGC internal network. Attackers exfiltrated geological survey data and internal communications.", "attack_type": "data_breach", "attack_vector": "unknown", "target_sector": "government", "country": "India", "severity": "high", "target_org": "ONGC", "source_name": "Economic Times", "status": "verified", "confidence_score": 0.80, "verified": "partial"},
    {"title": "Pakistan OGDCL Oil Company Cyber Attack", "description": "OGDCL Pakistan suffered cyberattack disrupting internal operations and data management systems.", "attack_type": "malware", "attack_vector": "unknown", "target_sector": "government", "country": "Pakistan", "severity": "high", "target_org": "OGDCL Pakistan", "source_name": "Dawn", "status": "verified", "confidence_score": 0.83, "verified": "yes"},
    {"title": "Nepal Army Website DDoS Attack", "description": "DDoS attack targeting Nepal Army official website taking it offline for several hours. Claimed by hacktivist group.", "attack_type": "ddos", "attack_vector": "web", "target_sector": "government", "country": "Nepal", "severity": "medium", "target_org": "Nepal Army", "source_name": "Setopati", "status": "verified", "confidence_score": 0.80, "verified": "partial"},
    {"title": "India Swiggy Credential Stuffing Attack", "description": "Credential stuffing attack on Swiggy accounts using leaked credentials. Thousands of accounts hijacked for fraudulent food orders.", "attack_type": "other", "attack_vector": "web", "target_sector": "ecommerce", "country": "India", "severity": "medium", "target_org": "Swiggy", "source_name": "CERT-In", "status": "verified", "confidence_score": 0.84, "verified": "yes"},
    {"title": "Pakistan PIA Airline Data Breach", "description": "Pakistan International Airlines data breach exposing employee records, flight schedules, and internal communications.", "attack_type": "data_breach", "attack_vector": "unknown", "target_sector": "government", "country": "Pakistan", "severity": "medium", "target_org": "Pakistan International Airlines", "source_name": "ARY News", "status": "verified", "confidence_score": 0.82, "verified": "yes"},
    {"title": "Bangladesh Rupali Bank Phishing Attack", "description": "State-owned Rupali Bank customers targeted by phishing via fake internet banking portal. Multiple unauthorized transactions reported.", "attack_type": "phishing", "attack_vector": "email", "target_sector": "banking", "country": "Bangladesh", "severity": "high", "target_org": "Rupali Bank customers", "source_name": "BGD e-GOV CIRT", "status": "verified", "confidence_score": 0.86, "verified": "yes"},
    {"title": "Bhutan Government Portal Defacement", "description": "Multiple Bhutanese government websites including Royal Civil Service Commission portal defaced by hacktivists.", "attack_type": "defacement", "attack_vector": "web", "target_sector": "government", "country": "Bhutan", "severity": "low", "source_name": "Zone-H", "status": "verified", "confidence_score": 0.78, "verified": "partial"},
    {"title": "India HDFC Life Insurance Data Extortion", "description": "Threat actor claimed to have stolen data of 8 million HDFC Life policyholders including medical history and demanded ransom.", "attack_type": "data_breach", "attack_vector": "unknown", "target_sector": "banking", "country": "India", "severity": "high", "target_org": "HDFC Life Insurance", "source_name": "Economic Times", "status": "verified", "confidence_score": 0.88, "verified": "yes"},
    {"title": "India UPI Vishing and Fake QR Code Fraud Surge", "description": "NPCI reported surge in UPI fraud including vishing calls, fake payment links, and malicious QR codes. Over Rs 1000 crore in losses.", "attack_type": "social_engineering", "attack_vector": "phone", "target_sector": "banking", "country": "India", "severity": "high", "source_name": "NPCI / RBI", "status": "verified", "confidence_score": 0.92, "verified": "yes"},
]


def seed():
    db = SessionLocal()
    try:
        added = 0
        for item in ATTACKS:
            duplicate = (
                db.query(models.Attack)
                .filter(models.Attack.title == item["title"])
                .first()
            )
            if duplicate:
                continue
            attack = models.Attack(**item)
            db.add(attack)
            added += 1
        db.commit()
        print(f"[seed] Successfully seeded {added} attacks.")
    except Exception as e:
        db.rollback()
        print(f"[seed] Error: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed()